name: Run Query Tester

# Triggers the workflow weekly on Mondays at 6:54 am
  schedule:
    - cron: '54 6 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: anitacaron/ccf-tools-dep:v1.0.4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: 
        env:
          DEFAULT_BRANCH: master
        run: mkdir -p results && python src/query_tester.py --input tests
