name: Run Query Tester

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: anitacaron/ccf-tools-dep:v1.0.5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: 
        env:
          DEFAULT_BRANCH: master
        run: mkdir -p results && python src/query_tester.py --input tests 2> results/tests_log.txt
      - name: Define repository's owner
        run: chown -R root /__w/ccf_owl_query_tester/ccf_owl_query_tester
      - name: Commit tests log
        run: |
          git config --global user.name 'Anita Caron'
          git config --global user.email 'anitacaron@users.noreply.github.com'
          git add results/tests_log.txt
          git commit -m "Automated test"
          git push origin main
